### ISSUE TITLE
Add Nightmode

### ISSUE THREAD

**Issue by xroboter** [sea-watch/SAR-Client#9]
Add nightmode that inverts the colors on the map, should be quite easy to implement:

```css
#map.nightmode img{
   filter: invert(100%);
}
```
